export const ACTION1 = "ACTION1";
export const ACTION2 = "ACTION2";

export const STARTCOUNTDOWNSECOND1 = "STARTCOUNTDOWNSECOND1";
export const STOPCOUNTDOWNSECOND1 = "STOPCOUNTDOWNSECOND1";

export const UPDATECOUNTDOWNSECOND1 = "UPDATECOUNTDOWNSECOND1";
export const RESETCOUNTDOWNSECOND1 = "RESETCOUNTDOWNSECOND1";
export const SETINITCOUNTERSECOND1 = "SETINITCOUNTERSECOND1";
